server {
    listen 80;
    server_name _;

    access_log /dev/stdout;
    error_log /dev/stderr;

    location = / {
        # Змінено 127.0.0.1 на app (ім'я сервісу в docker-compose)
        proxy_pass http://app:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /items {
        proxy_pass http://app:8080/items;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        return 404;
    }
}